
/**
 * This class contains methods to return random numbers as generated by Random.org's atmospheric noise randomness generator. This makes the random numbers in the casino not psuedorandom and removes the option for someone to break the casino by figuring out the pattern for random numbers.
 * @author Adhitya Thirumala
 */
public class Random {
    private ReferenceStack<Integer> randomIntegers;

    public Random(String apiKey){
        JSONRPC2Reques
    }



    //methods i need: generate one integer, flip one coin, roll one dice, generate N integers with replacement, generate n integers without replacement, flip n coins, roll n dice.


}
